apiVersion: v1
kind: Secret
metadata:
  name: kratos-env
  namespace: kratos-staging
type: Opaque
data:
  DSN: >-
    cHJvZHVjdGlvbg==
  ENV: cHJvZHVjdGlvbg==
  LOG_LEVEL: dHJhY2U=
  SQA_OPT_OUT: dHJ1ZQ==